export type Address = {
  id?: string;
  city: string;
  state: string;
  patientId: string;
};

export type Admin = {
  name: string;
  password: string;
};

export type Client = {
  id: string;
  name: string;
  birthdate: Date;
  peopleWhoLivesWith: number;
  perCapitaIncome: number;
  schooling: string;
  hemodialysis: boolean;
  DPOCHistory: boolean;
  respiratoryProblem: boolean;
  healthyEating: boolean;
  anxiety: string;
  emotionalLackOfControl: string;
  insomnia: string;
  gender: string;
  alcoholFrequence: string;
  smokingFrequence: string;
  workoutFrequence: string;
  historicOfCancer: string;
  historicOfDiabetes: string;
  historicOfObesity: string;
};

export type Metrics = {
  question: string;
  value: number;
  illnessId: string;
};

export type Illness = {
  id?: string;
  name: string;
  percentege?: string;
  cost?: string;
  averageAge?: string;
  womenPercentage?: string;
  diseasedClients?: Client[];
  illnessMetrics?: Metrics[];
};

export type Diagnose = {
  userId: string;
  illness: string;
  illnessRate: number;
  resetDate: Date | string;
};

export type Service = {
  id: string;
  code: string;
  date: Date;
  professional: string;
  description: string;
  cost: string;
  patientId: string;
};

export const selectColor = (percentage: number) => {
  if (percentage < 30) {
    return "bg-blue-400";
  } else if (percentage < 55) {
    return "bg-green-500";
  } else if (percentage < 95) {
    return "bg-yellow-400";
  } else {
    return "bg-red-500";
  }
};

export const users = [
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
  {
    alcoholFrequence: "Nunca",
    anxiety: "Nunca",
    birthdate: new Date("1999-01-01"),
    DPOCHistory: false,
    emotionalLackOfControl: "Nunca",
    gender: "Masculino",
    healthyEating: true,
    hemodialysis: false,
    historicOfCancer: "Nunca",
    historicOfDiabetes: "Nunca",
    historicOfObesity: "Nunca",
    id: "1",
    insomnia: "Nunca",
    name: "João",
    peopleWhoLivesWith: 1,
    perCapitaIncome: 1000,
    respiratoryProblem: false,
    schooling: "Ensino Superior",
    smokingFrequence: "Nunca",
    workoutFrequence: "Nunca",
  },
] as Client[];
